name: CI

on: [push]

jobs:
  ci:
    name: CI
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            python: "3.10"
            toxenv: py
          - os: ubuntu-latest
            python: "3.10"
            toxenv: linters
          - os: ubuntu-latest
            python: "3.10"
            toxenv: "security"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
          cache: "pip"
      - run: python -m pip install --upgrade setuptools pip tox==4.4.7 virtualenv
      - run: tox -e ${{ matrix.toxenv }}
  build:
    needs: [ci]
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: ${{ secrets.GCLOUD_SERVICE_KEY }}
      - name: build-container
        run: |
          gcloud auth configure-docker --quiet
          docker build \
            -t us.gcr.io/etl-projects-390007/random-csv-etl:${{ github.sha }} \
            -t us.gcr.io/etl-projects-390007/random-csv-etl:latest \
            --build-arg BUILDKIT_INLINE_CACHE=1 \
            .
      - name: push-container
        run: |
          docker push us.gcr.io/etl-projects-390007/random-csv-etl:${{ github.sha }}
          docker push us.gcr.io/etl-projects-390007/random-csv-etl:latest
